apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: hasanheroglu/pingpong:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "3001"
