apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: 
        - name: shared-output
          emptyDir: {}
      containers:
      - name: logoutputwriter
        image: hasanheroglu/log-output-writer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env: 
          - name: PORT
            value: "4000"
        volumeMounts:
          - name: shared-output
            mountPath: /usr/src/app/files
      - name: logoutputreader
        image: hasanheroglu/log-output-reader:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: shared-output
            mountPath: /usr/src/app/files
